config/routes.rb
Rails.application.routes.draw do
  resources :videos

  root to: 'visitors#index'
  get '/support', to: 'visitors#support'
  get '/stats', to: 'visitors#stats'

  devise_for :users
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base

  validate :check_link
  belongs_to :user
  self.per_page = 10

  def frame
    %Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ self.link }" frameborder="0" allowfullscreen></iframe>}
  end

  private

  def check_link
    if self.link[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      self.link[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    if youtube_id.blank?
      errors.add(:link, "invalid youtube link")
    else
      self.link = youtube_id
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout

  private

  def layout
    # only turn it off for login pages:
    (is_a?(Devise::SessionsController) || is_a?(Devise::RegistrationsController)) ? 'devise' : "application"
    # or turn layout off for every devise controller:
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.paginate(:page => params[:page])

  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
    @video.user = current_user
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user = current_user

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:description, :link, :user_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    %h3.green-color
      %i.fa.fa-shield
      OnePlus
      %strong Reviews
      %br
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Submit a video', new_video_path  if user_signed_in? %></li>
<li><%= link_to 'User videos', videos_path %></li>
<li><%= link_to 'Support cycle', support_path %></li>
<li><%= link_to 'Stats', stats_path %></li>
<% if user_signed_in? %>
<li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %meta{:content => "OnePlus reviews offers real-user experiences with OnePlus devices and their support", :name => "description"}
    %meta{:content => "Stijn", :name => "author"}
    %link{:href => "//fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,600,700", :rel => "stylesheet"}/
    %title= content_for?(:title) ? yield(:title) : 'Oneplus Reviews'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Oneplus Reviews'}"}
    = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .page-wrapper
      .page-container
        .main-container
          %header
            = render 'layouts/navigation'
          .page-content
            = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %meta{:content => "OnePlus reviews offers real-user experiences with OnePlus devices and their support", :name => "description"}
    %meta{:content => "Stijn", :name => "author"}
    %link{:href => "//fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,600,700", :rel => "stylesheet"}/
    %title= content_for?(:title) ? yield(:title) : 'Oneplus Reviews'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Oneplus Reviews'}"}
    = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/videos/_form.html.haml
= simple_form_for(@video) do |f|
  = f.error_notification

  .form-inputs
    = f.input :link, :placeholder => 'Paste in your youtube link here'
    = f.input :description, as: :text, :placeholder => 'Optional: you can enter a description of the problem here'

  .form-actions
    = f.button :submit

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h3 Some footage of OnePlus phones:
- if current_user.nil?
  %h4 You can submit your own video by logging in
- else
  %h4= link_to 'Submit your own youtube video', new_video_path
%h5

- @videos.each do |video|
  = raw(video.frame)
  %h5=  video.description if !video.description.nil?
  .text-muted= 'Added by: ' + video.user.name if !video.user.nil?
  .text-muted= 'Added on: ' + video.created_at.to_s(:long)
  %p


= will_paginate @videos

app/views/videos/new.html.haml
%h2 Add your video to our collection

= render 'form'

app/views/videos/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @video.description
%p
  %b Link:
  = @video.link
%p
  %b User:
  = @video.user_id

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path

app/views/visitors/index.html.haml
%h2 Welcome to Oneplus Reviews

%h4.green-color What is this site about?
%h5 My experience with support has been so appalling that I took the time to setup this website in order to warn new potential customers about OnePlus, and to gather feedback of other users who've been confronted by the total lack of support from OnePlus.
%h5 Right now it's a very basic site, where we can gather user videos of their phones.  Since OnePlus support forces everybody to make a video that shouldn't be a problem :-)

%h4.green-color Plans for this site
%h5 Well depending on the popularity I plan to add stats where you can see the number of who users registered their phones, number of days between ticket creation and RMA, technical info etc...  Another addition would be 'hilarious customer support threads' where users you can vote on the most painful user experience.

%h4.green-color Why go through all the trouble?
%h5 Nobody likes getting left in the cold.  OnePlus customer support is toying with us, only trying to gain time, while lots of users are experiencing real issues that are rendering their phone completely useless (ghost touches).
%h5
  %strong NEVER SETTLE
  , that's the tagline of OnePlus.  Well, they can rest assured:
  %strong we won't!

app/views/visitors/stats.html.haml
%h3 Support stats
%h5 Here comes a page where users can indicate when a support call was made, when support replied, when they got an RMA, if the problem is still ongoing, etc...

app/views/visitors/support.html.haml
%h3 How does a regular support ticket migrate at OnePlus?
%h5 Content about how a typical support ticket is handled at OnePlus, which questions does a customer get, through which hoops does he need to jump to be able to get a justified RMA.
%h5 Content welcome...